// apps/desktop/src/components/TabBar.tsx
import { useEffect, useRef, useState } from "react";
import { Button, Tab, TabList, tokens } from "@fluentui/react-components";
import { AddRegular, DismissRegular } from "@fluentui/react-icons";
import { DialectIcon } from "./DialectIcon";

export interface TabItem {
  id: string;
  title: string;
  dirty?: boolean;
  dialect?: string;
}

export interface TabBarProps {
  tabs: TabItem[];
  activeTabId: string | null;
  onSelect?: (id: string) => void;
  onClose?: (id: string) => void;
  onAdd?: () => void;
  onRename?: (id: string, title: string) => void;
}

export function TabBar({ tabs, activeTabId, onSelect, onClose, onAdd, onRename }: TabBarProps) {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingValue, setEditingValue] = useState("");
  const inputRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (editingId && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [editingId]);

  const commitRename = () => {
    if (editingId) {
      const trimmed = editingValue.trim();
      if (trimmed) onRename?.(editingId, trimmed);
    }
    setEditingId(null);
  };

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: 4,
        padding: "4px 8px",
        borderBottom: `1px solid ${tokens.colorNeutralStroke1}`,
        background: tokens.colorNeutralBackground1,
      }}
    >
      <TabList
        selectedValue={activeTabId ?? undefined}
        onTabSelect={(_, data) => onSelect?.(String(data.value))}
      >
        {tabs.map((tab) => (
          <Tab key={tab.id} value={tab.id}>
            {editingId === tab.id ? (
              <input
                ref={inputRef}
                value={editingValue}
                onChange={(e) => setEditingValue(e.target.value)}
                onBlur={commitRename}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    commitRename();
                  } else if (e.key === "Escape") {
                    e.preventDefault();
                    setEditingId(null);
                  }
                }}
                onClick={(e) => e.stopPropagation()}
                style={{ width: 120, font: "inherit" }}
              />
            ) : (
              <div
                style={{ display: "flex", alignItems: "center", gap: 4, fontSize: 13 }}
              >
                <span
                  onDoubleClick={(e) => {
                    e.stopPropagation();
                    setEditingId(tab.id);
                    setEditingValue(tab.title);
                  }}
                  style={{ display: "flex", alignItems: "center", gap: 4, flex: 1, overflow: "hidden" }}
                >
                  {tab.dialect && (
                    <span title={tab.dialect} style={{ fontSize: 12, lineHeight: 1, display: "flex" }}>
                      <DialectIcon dialect={tab.dialect} size={12} />
                    </span>
                  )}
                  <span style={{ fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                    {tab.title}
                  </span>
                  {tab.dirty && (
                    <span style={{ color: tokens.colorPaletteYellowForeground1, fontSize: 8 }}>●</span>
                  )}
                </span>
                <Button
                  icon={<DismissRegular />}
                  appearance="transparent"
                  size="small"
                  onClick={(e) => {
                    e.stopPropagation();
                    onClose?.(tab.id);
                  }}
                  aria-label="Fechar aba"
                />
              </div>
            )}
          </Tab>
        ))}
      </TabList>
      <Button icon={<AddRegular />} size="small" appearance="subtle" onClick={onAdd} aria-label="Nova aba" />
    </div>
  );
}

// apps/desktop/src/lib/TabBar.svelte
<script lang="ts" module>
  export function focusOnMount(node: HTMLInputElement) {
    node.focus();
    node.select();
  }
</script>

<script lang="ts">
  import DialectIcon from "./DialectIcon.svelte";

  interface TabInfo {
    id: string;
    title: string;
    dirty?: boolean;
    dialect?: string;
  }

  interface Props {
    tabs: TabInfo[];
    activeTabId: string | null;
    onSelect?: (id: string) => void;
    onClose?: (id: string) => void;
    onAdd?: () => void;
    onRename?: (id: string, title: string) => void;
  }
  let { tabs, activeTabId, onSelect, onClose, onAdd, onRename }: Props = $props();

  let editingId = $state<string | null>(null);
  let editingValue = $state("");

  function onTabClick(id: string) {
    if (editingId !== id) onSelect?.(id);
  }

  function onCloseClick(e: Event, id: string) {
    e.preventDefault();
    e.stopPropagation();
    onClose?.(id);
  }

  function onAddClick(e: Event) {
    e.preventDefault();
    onAdd?.();
  }

  function startRename(e: Event, tab: TabInfo) {
    e.preventDefault();
    e.stopPropagation();
    editingId = tab.id;
    editingValue = tab.title;
  }

  function commitRename() {
    if (editingId) {
      const trimmed = editingValue.trim();
      if (trimmed) onRename?.(editingId, trimmed);
    }
    editingId = null;
  }

  function onRenameKeydown(e: KeyboardEvent) {
    if (e.key === "Enter") {
      e.preventDefault();
      commitRename();
    } else if (e.key === "Escape") {
      e.preventDefault();
      editingId = null;
    }
  }

  function onTabMousedown(e: MouseEvent, id: string) {
    if (e.button === 1) {
      e.preventDefault();
      onClose?.(id);
    }
  }

  function onTabKeydown(e: KeyboardEvent, id: string) {
    if (editingId === id) return;
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      onSelect?.(id);
    }
  }
</script>

<div class="tab-bar" role="tablist">
  {#each tabs as tab (tab.id)}
    <div
      class="tab"
      class:active={tab.id === activeTabId}
      role="tab"
      aria-selected={tab.id === activeTabId}
      tabindex="0"
      onclick={() => onTabClick(tab.id)}
      onmousedown={(e) => onTabMousedown(e, tab.id)}
      ondblclick={(e) => startRename(e, tab)}
      onkeydown={(e) => onTabKeydown(e, tab.id)}
    >
      {#if editingId === tab.id}
        <input
          class="tab-rename"
          bind:value={editingValue}
          onblur={commitRename}
          onkeydown={onRenameKeydown}
          onclick={(e) => e.stopPropagation()}
          use:focusOnMount
        />
      {:else}
        {#if tab.dialect}
          <DialectIcon dialect={tab.dialect} size={12} />
        {/if}
        <span class="tab-title" title={tab.title}>{tab.title}</span>
        {#if tab.dirty}
          <span class="tab-dirty" title="Alterações não salvas">●</span>
        {/if}
      {/if}
      <button
        class="tab-close"
        title="Fechar aba"
        aria-label="Fechar aba"
        onclick={(e) => onCloseClick(e, tab.id)}
      >×</button>
    </div>
  {/each}
  <button class="tab-add" title="Nova aba" aria-label="Nova aba" onclick={onAddClick}>+</button>
</div>

<style>
  .tab-bar {
    display: flex;
    align-items: stretch;
    background: #252526;
    border-bottom: 1px solid #333;
    overflow-x: auto;
    flex-shrink: 0;
  }
  .tab {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 6px 8px 6px 12px;
    background: #2d2d2d;
    border-right: 1px solid #1e1e1e;
    color: #a0a0a0;
    font-size: 12px;
    cursor: pointer;
    user-select: none;
    white-space: nowrap;
    max-width: 200px;
  }
  .tab:hover { background: #333333; }
  .tab.active {
    background: #1e1e1e;
    color: #ddd;
    box-shadow: inset 0 -2px 0 #0e639c;
  }
  .tab-title {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .tab-dirty {
    color: #e2b93d;
    font-size: 8px;
    line-height: 1;
    flex-shrink: 0;
  }
  .tab-rename {
    background: #1e1e1e;
    color: #ddd;
    border: 1px solid #0e639c;
    border-radius: 2px;
    font-size: 12px;
    padding: 1px 4px;
    width: 120px;
    font-family: inherit;
  }
  .tab-close {
    border: none;
    background: transparent;
    color: inherit;
    opacity: 0.6;
    cursor: pointer;
    font-size: 14px;
    line-height: 1;
    padding: 0 2px;
    border-radius: 3px;
  }
  .tab-close:hover { opacity: 1; background: #444; }
  .tab-add {
    border: none;
    background: transparent;
    color: #a0a0a0;
    cursor: pointer;
    font-size: 15px;
    padding: 0 12px;
    line-height: 1;
  }
  .tab-add:hover { color: #fff; background: #333333; }
</style>
