// apps/desktop/src/lib/ConnectionDialog.svelte
<script lang="ts">
  import type { ConnectionConfig } from "@omni-sql/ts-types";
  import { backend } from "./backend";
  import { pickJarPath } from "./file-io";

  interface Props {
    open: boolean;
    editing?: ConnectionConfig | null;
    onClose: () => void;
    onSaved: () => void;
  }
  let { open, editing = null, onClose, onSaved }: Props = $props();

  type Mode = "postgres" | "oracle" | "mysql" | "mariadb" | "sqlserver" | "jdbc-generic" | "demo";

  const DEFAULT_PORTS: Record<Mode, string> = {
    postgres: "5432",
    oracle: "1521",
    mysql: "3306",
    mariadb: "3306",
    sqlserver: "1433",
    "jdbc-generic": "",
    demo: "5432",
  };
  const DEFAULT_DATABASES: Record<Mode, string> = {
    postgres: "postgres",
    oracle: "orcl",
    mysql: "app",
    mariadb: "app",
    sqlserver: "master",
    "jdbc-generic": "",
    demo: "postgres",
  };
  const DEFAULT_USERS: Record<Mode, string> = {
    postgres: "postgres",
    oracle: "system",
    mysql: "root",
    mariadb: "root",
    sqlserver: "sa",
    "jdbc-generic": "",
    demo: "postgres",
  };

  const KNOWN_DIALECTS = new Set<Mode>(["postgres", "oracle", "mysql", "mariadb", "sqlserver"]);

  function isKnownDialect(d: string): d is Exclude<Mode, "demo"> {
    return KNOWN_DIALECTS.has(d as Mode);
  }

  let mode = $state<Mode>("postgres");
  let label = $state("");
  let id = $state("");
  let host = $state("");
  let port = $state("5432");
  let database = $state("postgres");
  let user = $state("");
  let password = $state("");
  let ssl = $state(false);
  let jdbcUrl = $state("");
  let jarPath = $state("");
  let driverClassName = $state("");
  let busy = $state(false);
  let testResult = $state<{ ok: boolean; latencyMs: number; message?: string } | null>(null);
  let error = $state<string | null>(null);
  let availableSchemas = $state<string[] | null>(null);
  let selectedSchemas = $state<Set<string>>(new Set());
  let schemasLoading = $state(false);

  $effect(() => {
    if (open) {
      const editingDialect = editing?.dialect;
      const isKnown = editingDialect !== undefined && isKnownDialect(editingDialect);
      const isJdbcGeneric = editingDialect === "jdbc-generic";
      mode = isKnown ? editingDialect : isJdbcGeneric ? "jdbc-generic" : "demo";
      label = editing?.label ?? "";
      id = editing?.id ?? "";
      user = editing?.user ?? "";
      password = "";
      ssl = editing?.options?.ssl === true || editing?.options?.ssl === "require";
      if (isKnown) {
        const parts = parseEndpoint(editing!.endpoint, DEFAULT_PORTS[mode]);
        host = parts.host;
        port = parts.port;
        database = parts.database;
      } else {
        host = "";
        port = "5432";
        database = "postgres";
      }
      if (isJdbcGeneric) {
        jdbcUrl = editing?.endpoint ?? "";
        jarPath = String(editing?.options?.jarPath ?? "");
        driverClassName = String(editing?.options?.driverClassName ?? "");
      } else {
        jdbcUrl = "";
        jarPath = "";
        driverClassName = "";
      }
      testResult = null;
      error = null;
      busy = false;
      availableSchemas = null;
      selectedSchemas = new Set(editing?.schemas ?? []);
      if (isKnown && editing?.schemas && editing.schemas.length > 0) {
        void loadSchemas();
      }
    }
  });

  function parseEndpoint(
    endpoint: string,
    defaultPort = "5432",
  ): { host: string; port: string; database: string } {
    // Expects "host:port/database"
    const [hostPort, db] = endpoint.split("/");
    const [h, p] = hostPort?.split(":") ?? ["", ""];
    return { host: h ?? "", port: p ?? defaultPort, database: db ?? "postgres" };
  }

  const ALL_MODES: Mode[] = ["postgres", "oracle", "mysql", "mariadb", "sqlserver"];

  function onModeChange(e: Event): void {
    const next = (e.currentTarget as HTMLSelectElement).value as Mode;
    const isDefaultPort = port === "" || ALL_MODES.some((m) => port === DEFAULT_PORTS[m]);
    const isDefaultDatabase = database === "" || ALL_MODES.some((m) => database === DEFAULT_DATABASES[m]);
    const isDefaultUser = user === "" || ALL_MODES.some((m) => user === DEFAULT_USERS[m]);
    mode = next;
    if (next === "demo" || next === "jdbc-generic") return;
    if (isDefaultPort) port = DEFAULT_PORTS[next];
    if (isDefaultDatabase) database = DEFAULT_DATABASES[next];
    if (isDefaultUser) user = DEFAULT_USERS[next];
  }

  function buildEndpoint(): string {
    if (mode === "jdbc-generic") return jdbcUrl;
    return `${host}:${port}/${database}`;
  }

  function buildOptions(): ConnectionConfig["options"] {
    if (mode === "jdbc-generic") return { jarPath, driverClassName };
    return ssl ? { ssl: "require" } : undefined;
  }

  function defaultLabel(): string {
    if (mode === "jdbc-generic") return jdbcUrl || "JDBC genérico";
    return `${host}/${database}`;
  }

  function canConnect(): boolean {
    if (mode === "jdbc-generic") {
      return jdbcUrl.length > 0 && jarPath.length > 0 && driverClassName.length > 0 && user.length > 0;
    }
    return host.length > 0 && user.length > 0;
  }

  async function onPickJar(e: Event) {
    e.preventDefault();
    const picked = await pickJarPath();
    if (picked) jarPath = picked;
  }

  function generateId(): string {
    return `conn-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`;
  }

  async function onTest(e: Event) {
    e.preventDefault();
    if (mode === "demo") return;
    busy = true;
    testResult = null;
    error = null;
    try {
      const cfg: ConnectionConfig = {
        id: id || generateId(),
        label: label || defaultLabel(),
        dialect: mode,
        endpoint: buildEndpoint(),
        user,
        options: buildOptions(),
      };
      testResult = await backend.call("connection.test", { config: cfg, password });
    } catch (e) {
      error = (e as Error).message;
    } finally {
      busy = false;
    }
  }

  function toggleSchema(name: string) {
    const next = new Set(selectedSchemas);
    if (next.has(name)) next.delete(name);
    else next.add(name);
    selectedSchemas = next;
  }

  async function loadSchemas() {
    if (mode === "demo") return;
    schemasLoading = true;
    error = null;
    try {
      const cfg: ConnectionConfig = {
        id: id || generateId(),
        label: label || defaultLabel(),
        dialect: mode,
        endpoint: buildEndpoint(),
        user,
        options: buildOptions(),
      };
      const res = await backend.call<{ schemas: string[] }>("connection.listSchemas", { config: cfg, password });
      availableSchemas = [...res.schemas];
    } catch (e) {
      error = (e as Error).message;
    } finally {
      schemasLoading = false;
    }
  }

  function onLoadSchemasClick(e: Event) {
    e.preventDefault();
    void loadSchemas();
  }

  async function onSave(e: Event) {
    e.preventDefault();
    busy = true;
    error = null;
    try {
      const cfg: ConnectionConfig =
        mode === "demo"
          ? {
              id: id || "demo",
              label: label || "Demo (in-memory)",
              dialect: "postgres",
              endpoint: "memory://local",
              user: user || "anon",
            }
          : {
              id: id || generateId(),
              label: label || defaultLabel(),
              dialect: mode,
              endpoint: buildEndpoint(),
              user,
              options: buildOptions(),
              schemas: selectedSchemas.size > 0 ? [...selectedSchemas] : undefined,
            };
      await backend.call("connection.add", { config: cfg, password });
      onSaved();
    } catch (e) {
      error = (e as Error).message;
      busy = false;
    }
  }

  let mouseDownOnBackdrop = $state(false);

  function onBackdropMouseDown(e: MouseEvent) {
    mouseDownOnBackdrop = e.target === e.currentTarget;
  }
  function onBackdropMouseUp(e: MouseEvent) {
    if (mouseDownOnBackdrop && e.target === e.currentTarget) {
      onClose();
    }
    mouseDownOnBackdrop = false;
  }
  function onBackdropKey(e: KeyboardEvent) {
    if (e.key === "Escape") onClose();
  }
</script>

{#if open}
  <div class="backdrop" onmousedown={onBackdropMouseDown} onmouseup={onBackdropMouseUp} onkeydown={onBackdropKey} role="dialog" tabindex="-1" aria-modal="true" aria-labelledby="conn-title">
    <form class="dialog" onsubmit={onSave}>
      <h2 id="conn-title">{editing ? "Editar conexão" : "Nova conexão"}</h2>

      <label>
        <span>Tipo</span>
        <select value={mode} onchange={onModeChange} disabled={busy}>
          <option value="postgres">PostgreSQL</option>
          <option value="mysql">MySQL</option>
          <option value="mariadb">MariaDB</option>
          <option value="sqlserver">SQL Server</option>
          <option value="oracle">Oracle</option>
          <option value="jdbc-generic">JDBC genérico</option>
          <option value="demo">Demo (in-memory)</option>
        </select>
      </label>

      <label>
        <span>Nome</span>
        <input type="text" bind:value={label} placeholder="Minha conexão" disabled={busy} required />
      </label>

      {#if mode === "jdbc-generic"}
        <label>
          <span>JDBC URL</span>
          <input type="text" bind:value={jdbcUrl} placeholder="jdbc:exemplo://host:porta/db" disabled={busy} required />
        </label>

        <label>
          <span>Driver (.jar)</span>
          <div class="row">
            <input type="text" class="grow" bind:value={jarPath} placeholder="/caminho/para/driver.jar" disabled={busy} required />
            <button type="button" class="secondary" onclick={onPickJar} disabled={busy}>Procurar…</button>
          </div>
        </label>

        <label>
          <span>Classe do driver</span>
          <input type="text" bind:value={driverClassName} placeholder="com.exemplo.Driver" disabled={busy} required />
        </label>

        <label>
          <span>Usuário</span>
          <input type="text" bind:value={user} disabled={busy} required />
        </label>

        <label>
          <span>Senha</span>
          <input type="password" bind:value={password} placeholder="••••••" disabled={busy} />
        </label>

        <p class="hint">
          Carrega o driver via sidecar JVM — rode <code>services/jvm-sidecar</code> antes de conectar. Autocomplete/introspecção
          de schema ainda não é suportada para este dialeto; a grade de resultados funciona normalmente.
        </p>
      {/if}

      {#if mode !== "demo" && mode !== "jdbc-generic"}
        <div class="row">
          <label class="grow">
            <span>Host</span>
            <input type="text" bind:value={host} placeholder="127.0.0.1" disabled={busy} required />
          </label>
          <label>
            <span>Porta</span>
            <input type="text" bind:value={port} placeholder={DEFAULT_PORTS[mode]} disabled={busy} required />
          </label>
        </div>

        <label>
          <span>{mode === "oracle" ? "Service name / SID" : "Database"}</span>
          <input type="text" bind:value={database} placeholder={DEFAULT_DATABASES[mode]} disabled={busy} required />
        </label>

        <label>
          <span>Usuário</span>
          <input type="text" bind:value={user} placeholder={DEFAULT_USERS[mode]} disabled={busy} required />
        </label>

        <label>
          <span>Senha</span>
          <input type="password" bind:value={password} placeholder="••••••" disabled={busy} />
        </label>

        <label class="inline">
          <input type="checkbox" bind:checked={ssl} disabled={busy} />
          <span>SSL require</span>
        </label>

        <div class="schemas-section">
          <div class="schemas-header">
            <span>Schemas a indexar</span>
            <button
              type="button"
              class="link"
              onclick={onLoadSchemasClick}
              disabled={busy || schemasLoading || !canConnect()}
            >{schemasLoading ? "Carregando…" : "Carregar schemas"}</button>
          </div>
          {#if availableSchemas === null}
            <p class="hint">Sem seleção: todos os schemas serão indexados.</p>
          {:else if availableSchemas.length === 0}
            <p class="hint">Nenhum schema encontrado.</p>
          {:else}
            <div class="schemas-actions">
              <button type="button" class="link" onclick={() => (selectedSchemas = new Set(availableSchemas))}>Selecionar todos</button>
              <button type="button" class="link" onclick={() => (selectedSchemas = new Set())}>Selecionar nenhum</button>
            </div>
            <div class="schemas-list">
              {#each availableSchemas as s}
                <label class="inline schema-item">
                  <input type="checkbox" checked={selectedSchemas.has(s)} onchange={() => toggleSchema(s)} />
                  <span>{s}</span>
                </label>
              {/each}
            </div>
          {/if}
        </div>
      {/if}

      {#if error}
        <div class="error">{error}</div>
      {/if}

      {#if testResult}
        <div class={testResult.ok ? "success" : "warn"}>
          {testResult.ok
            ? `Conectado em ${testResult.latencyMs}ms`
            : `Falha: ${testResult.message ?? "desconhecida"}`}
        </div>
      {/if}

      <div class="actions">
        {#if mode !== "demo"}
          <button type="button" onclick={onTest} disabled={busy || !canConnect()}>
            {busy ? "Testando…" : "Testar conexão"}
          </button>
        {/if}
        <div class="spacer"></div>
        <button type="button" class="secondary" onclick={onClose} disabled={busy}>Cancelar</button>
        <button type="submit" disabled={busy || (mode !== "demo" && !canConnect())}>
          {busy ? "Salvando…" : "Salvar"}
        </button>
      </div>
    </form>
  </div>
{/if}

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.6);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
  }
  .dialog {
    background: #252526;
    border: 1px solid #3c3c3c;
    border-radius: 8px;
    padding: 20px;
    width: 420px;
    max-width: 90vw;
    display: flex;
    flex-direction: column;
    gap: 12px;
    box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
  }
  h2 {
    margin: 0 0 4px;
    font-size: 16px;
    font-weight: 600;
  }
  label {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 12px;
    color: #ccc;
  }
  label.inline {
    flex-direction: row;
    align-items: center;
    gap: 8px;
  }
  .row {
    display: flex;
    gap: 12px;
  }
  .grow {
    flex: 1;
  }
  input, select {
    background: #1e1e1e;
    color: #ddd;
    border: 1px solid #3c3c3c;
    padding: 6px 8px;
    border-radius: 4px;
    font-size: 13px;
  }
  input:focus, select:focus {
    outline: none;
    border-color: #0e639c;
  }
  input:disabled, select:disabled {
    opacity: 0.6;
  }
  .actions {
    display: flex;
    gap: 10px;
    margin-top: 8px;
  }
  .spacer {
    flex: 1;
  }
  button {
    background: #0e639c;
    color: #fff;
    border: none;
    padding: 7px 14px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
  }
  button.secondary {
    background: #3c3c3c;
  }
  button:disabled {
    opacity: 0.5;
    cursor: default;
  }
  .schemas-section {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 8px;
    background: #1e1e1e;
    border: 1px solid #3c3c3c;
    border-radius: 4px;
  }
  .schemas-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    font-size: 12px;
    color: #ccc;
  }
  .schemas-actions {
    display: flex;
    gap: 10px;
  }
  .schemas-list {
    display: flex;
    flex-direction: column;
    gap: 2px;
    max-height: 140px;
    overflow-y: auto;
    padding-right: 4px;
  }
  .schema-item {
    font-size: 12px;
  }
  .hint {
    margin: 0;
    font-size: 11px;
    color: #888;
  }
  button.link {
    background: transparent;
    color: #4fa3e0;
    padding: 0;
    font-weight: 400;
    font-size: 12px;
    text-decoration: underline;
  }
  button.link:disabled {
    color: #666;
    text-decoration: none;
  }
  .error {
    color: #f48771;
    font-size: 12px;
  }
  .success {
    color: #89d185;
    font-size: 12px;
  }
  .warn {
    color: #f48771;
    font-size: 12px;
  }
</style>

// apps/desktop/src/components/ConnectionDialog.tsx
import { useCallback, useEffect, useState } from "react";
import {
  Button,
  Dialog,
  DialogSurface,
  DialogTitle,
  DialogBody,
  DialogActions,
  Input,
  Label,
  Checkbox,
  Text,
  tokens,
} from "@fluentui/react-components";
import type { ConnectionConfig } from "@omni-sql/ts-types";
import { backend } from "../lib/backend";
import { pickJarPath } from "../lib/file-io";
import { useLanguage } from "../i18n";

type Mode = "postgres" | "oracle" | "mysql" | "mariadb" | "sqlserver" | "jdbc-generic" | "demo";

const DEFAULT_PORTS: Record<Mode, string> = {
  postgres: "5432",
  oracle: "1521",
  mysql: "3306",
  mariadb: "3306",
  sqlserver: "1433",
  "jdbc-generic": "",
  demo: "5432",
};

const DEFAULT_DATABASES: Record<Mode, string> = {
  postgres: "postgres",
  oracle: "orcl",
  mysql: "app",
  mariadb: "app",
  sqlserver: "master",
  "jdbc-generic": "",
  demo: "postgres",
};

const DEFAULT_USERS: Record<Mode, string> = {
  postgres: "postgres",
  oracle: "system",
  mysql: "root",
  mariadb: "root",
  sqlserver: "sa",
  "jdbc-generic": "",
  demo: "postgres",
};

const ALL_MODES: Mode[] = ["postgres", "oracle", "mysql", "mariadb", "sqlserver"];

function isKnownDialect(d: string): d is Exclude<Mode, "demo" | "jdbc-generic"> {
  return new Set<Mode>(["postgres", "oracle", "mysql", "mariadb", "sqlserver"]).has(d as Mode);
}

function parseEndpoint(endpoint: string, defaultPort: string): { host: string; port: string; database: string } {
  const [hostPort, db] = endpoint.split("/");
  const [h, p] = hostPort?.split(":") ?? ["", ""];
  return { host: h ?? "", port: p ?? defaultPort, database: db ?? "postgres" };
}

function generateId(): string {
  return `conn-${crypto.randomUUID()}`;
}

export interface ConnectionDialogProps {
  open: boolean;
  editing?: ConnectionConfig | null;
  duplicating?: boolean;
  onClose: () => void;
  onSaved: (connectionId: string) => void | Promise<void>;
}

export function ConnectionDialog({ open, editing, duplicating = false, onClose, onSaved }: ConnectionDialogProps) {
  const { t } = useLanguage();
  const [mode, setMode] = useState<Mode>("postgres");
  const [label, setLabel] = useState("");
  const [id, setId] = useState("");
  const [host, setHost] = useState("");
  const [port, setPort] = useState("5432");
  const [database, setDatabase] = useState("postgres");
  const [user, setUser] = useState("");
  const [password, setPassword] = useState("");
  const [ssl, setSsl] = useState(false);
  const [jdbcUrl, setJdbcUrl] = useState("");
  const [jarPath, setJarPath] = useState("");
  const [driverClassName, setDriverClassName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [testResult, setTestResult] = useState<{ ok: boolean; latencyMs: number; message?: string } | null>(null);
  const [availableSchemas, setAvailableSchemas] = useState<string[] | null>(null);
  const [selectedSchemas, setSelectedSchemas] = useState<Set<string>>(new Set());

  useEffect(() => {
    if (!open) return;
    const editingDialect = editing?.dialect;
    const isKnown = editingDialect !== undefined && isKnownDialect(editingDialect);
    const isJdbc = editingDialect === "jdbc-generic";
    const nextMode = isKnown ? editingDialect : isJdbc ? "jdbc-generic" : "demo";
    setMode(nextMode);
    setLabel(editing?.label ?? "");
    setId(duplicating ? generateId() : editing?.id ?? "");
    setUser(editing?.user ?? "");
    setPassword("");
    setSsl(editing?.options?.ssl === true || editing?.options?.ssl === "require");
    if (isKnown) {
      const parts = parseEndpoint(editing!.endpoint, DEFAULT_PORTS[nextMode]);
      setHost(parts.host);
      setPort(parts.port);
      setDatabase(parts.database);
    } else {
      setHost("");
      setPort("5432");
      setDatabase("postgres");
    }
    if (isJdbc) {
      setJdbcUrl(editing?.endpoint ?? "");
      setJarPath(String(editing?.options?.jarPath ?? ""));
      setDriverClassName(String(editing?.options?.driverClassName ?? ""));
    } else {
      setJdbcUrl("");
      setJarPath("");
      setDriverClassName("");
    }
    setTestResult(null);
    setError(null);
    setBusy(false);
    setAvailableSchemas(null);
    setSelectedSchemas(new Set(editing?.schemas ?? []));
  }, [open, editing, duplicating]);

  const buildEndpoint = useCallback(() => {
    if (mode === "jdbc-generic") return jdbcUrl;
    return `${host}:${port}/${database}`;
  }, [mode, jdbcUrl, host, port, database]);

  const buildOptions = useCallback((): ConnectionConfig["options"] => {
    if (mode === "jdbc-generic") return { jarPath, driverClassName };
    return ssl ? { ssl: "require" } : undefined;
  }, [mode, jarPath, driverClassName, ssl]);

  const defaultLabel = useCallback(() => {
    if (mode === "jdbc-generic") return jdbcUrl || t("jdbcGeneric");
    return `${host}/${database}`;
  }, [mode, jdbcUrl, host, database, t]);

  const canConnect = useCallback(() => {
    if (mode === "jdbc-generic") {
      return jdbcUrl.length > 0 && jarPath.length > 0 && driverClassName.length > 0 && user.length > 0;
    }
    return host.length > 0 && user.length > 0;
  }, [mode, jdbcUrl, jarPath, driverClassName, user, host]);

  const buildConfig = useCallback((): ConnectionConfig => {
    if (mode === "demo") {
      return {
        id: id || "demo",
        label: label || "Demo (in-memory)",
        dialect: "postgres",
        endpoint: "memory://local",
        user: user || "anon",
      };
    }
    return {
      id: id || generateId(),
      label: label || defaultLabel(),
      dialect: mode,
      endpoint: buildEndpoint(),
      user,
      options: buildOptions(),
      schemas: selectedSchemas.size > 0 ? [...selectedSchemas] : undefined,
    };
  }, [mode, id, label, defaultLabel, buildEndpoint, user, buildOptions, selectedSchemas]);

  const onTest = async () => {
    if (mode === "demo") return;
    setBusy(true);
    setError(null);
    setTestResult(null);
    try {
      const result = await backend.call("connection.test", { config: buildConfig(), password });
      setTestResult(result as { ok: boolean; latencyMs: number; message?: string });
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  const loadSchemas = async () => {
    if (mode === "demo") return;
    setBusy(true);
    setError(null);
    try {
      const result = await backend.call<{ schemas: string[] }>("connection.listSchemas", {
        config: buildConfig(),
        password,
      });
      setAvailableSchemas(result.schemas);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  const onSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    try {
      const result = await backend.call<{ connectionId: string }>("connection.add", { config: buildConfig(), password });
      await onSaved(result.connectionId);
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setBusy(false);
    }
  };

  const onModeChange = (next: Mode) => {
    const isDefaultPort = port === "" || ALL_MODES.some((m) => port === DEFAULT_PORTS[m]);
    const isDefaultDatabase = database === "" || ALL_MODES.some((m) => database === DEFAULT_DATABASES[m]);
    const isDefaultUser = user === "" || ALL_MODES.some((m) => user === DEFAULT_USERS[m]);
    setMode(next);
    if (next === "demo" || next === "jdbc-generic") return;
    if (isDefaultPort) setPort(DEFAULT_PORTS[next]);
    if (isDefaultDatabase) setDatabase(DEFAULT_DATABASES[next]);
    if (isDefaultUser) setUser(DEFAULT_USERS[next]);
  };

  const pickJar = async () => {
    const picked = await pickJarPath();
    if (picked) setJarPath(picked);
  };

  const toggleSchema = (name: string) => {
    setSelectedSchemas((prev) => {
      const next = new Set(prev);
      if (next.has(name)) next.delete(name);
      else next.add(name);
      return next;
    });
  };

  return (
    <Dialog open={open} onOpenChange={(_, data) => !data.open && onClose()}>
      <DialogSurface>
        <form onSubmit={onSave}>
          <DialogTitle>{duplicating ? t("duplicateConnection") : editing ? t("editConnection") : t("newConnection")}</DialogTitle>
          <DialogBody style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            <Label>
              Tipo
              <select
                value={mode}
                onChange={(e) => onModeChange(e.target.value as Mode)}
                disabled={busy}
                style={{ display: "block", width: "100%", marginTop: 4, padding: 6 }}
              >
                <option value="postgres">PostgreSQL</option>
                <option value="mysql">MySQL</option>
                <option value="mariadb">MariaDB</option>
                <option value="sqlserver">SQL Server</option>
                <option value="oracle">Oracle</option>
                <option value="jdbc-generic">{t("jdbcGeneric")}</option>
                <option value="demo">Demo (in-memory)</option>
              </select>
            </Label>

            <Label>
              Nome
              <Input value={label} onChange={(_, data) => setLabel(data.value)} placeholder={t("connectionNamePlaceholder")} disabled={busy} required style={{ marginTop: 4 }} />
            </Label>

            {mode === "jdbc-generic" && (
              <>
                <Label>
                  JDBC URL
                  <Input value={jdbcUrl} onChange={(_, data) => setJdbcUrl(data.value)} placeholder="jdbc:exemplo://host:porta/db" disabled={busy} required style={{ marginTop: 4 }} />
                </Label>
                <Label>
                  Driver (.jar)
                  <div style={{ display: "flex", gap: 8, marginTop: 4 }}>
                    <Input value={jarPath} onChange={(_, data) => setJarPath(data.value)} placeholder="/caminho/para/driver.jar" disabled={busy} required style={{ flex: 1 }} />
                    <Button type="button" onClick={pickJar} disabled={busy}>Procurar…</Button>
                  </div>
                </Label>
                <Label>
                  Classe do driver
                  <Input value={driverClassName} onChange={(_, data) => setDriverClassName(data.value)} placeholder="com.exemplo.Driver" disabled={busy} required style={{ marginTop: 4 }} />
                </Label>
              </>
            )}

            {mode !== "demo" && mode !== "jdbc-generic" && (
              <>
                <div style={{ display: "flex", gap: 12 }}>
                  <Label style={{ flex: 1 }}>
                    Host
                    <Input value={host} onChange={(_, data) => setHost(data.value)} placeholder="127.0.0.1" disabled={busy} required style={{ marginTop: 4 }} />
                  </Label>
                  <Label>
                    {t("port")}
                    <Input value={port} onChange={(_, data) => setPort(data.value)} placeholder={DEFAULT_PORTS[mode]} disabled={busy} required style={{ width: 90, marginTop: 4 }} />
                  </Label>
                </div>
                <Label>
                  {mode === "oracle" ? "Service name / SID" : "Database"}
                  <Input value={database} onChange={(_, data) => setDatabase(data.value)} placeholder={DEFAULT_DATABASES[mode]} disabled={busy} required style={{ marginTop: 4 }} />
                </Label>
              </>
            )}

            {mode !== "demo" && (
              <>
                <Label>
                  {t("user")}
                  <Input value={user} onChange={(_, data) => setUser(data.value)} placeholder={DEFAULT_USERS[mode]} disabled={busy} required style={{ marginTop: 4 }} />
                </Label>
                <Label>
                  {t("password")}
                  <Input type="password" value={password} onChange={(_, data) => setPassword(data.value)} placeholder="••••••" disabled={busy} style={{ marginTop: 4 }} />
                  {duplicating && <Text size={200} style={{ color: tokens.colorNeutralForeground2 }}>{t("duplicatePasswordHint")}</Text>}
                </Label>
              </>
            )}

            {mode !== "demo" && (
              <>
                {mode !== "jdbc-generic" && (
                  <Checkbox label="SSL require" checked={ssl} onChange={(_, data) => setSsl(data.checked === true)} disabled={busy} />
                )}
                <div
                  style={{
                    border: `1px solid ${tokens.colorNeutralStroke1}`,
                    borderRadius: 4,
                    padding: 8,
                    display: "flex",
                    flexDirection: "column",
                    gap: 8,
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                    <Text size={200}>{t("schemasToIndex")}</Text>
                    <Button type="button" onClick={loadSchemas} disabled={busy || !canConnect()} size="small">
                      {t("loadSchemas")}
                    </Button>
                  </div>
                  {availableSchemas === null ? (
                    <Text size={200} style={{ color: tokens.colorNeutralForeground2 }}>
                      {t("noSelectionAllSchemas")}
                    </Text>
                  ) : availableSchemas.length === 0 ? (
                    <Text size={200}>{t("noSchemaFound")}</Text>
                  ) : (
                    <>
                      <div style={{ display: "flex", gap: 12 }}>
                        <Button type="button" appearance="subtle" size="small" onClick={() => setSelectedSchemas(new Set(availableSchemas))}>
                          {t("selectAll")}
                        </Button>
                        <Button type="button" appearance="subtle" size="small" onClick={() => setSelectedSchemas(new Set())}>
                          {t("selectNone")}
                        </Button>
                      </div>
                      <div style={{ maxHeight: 140, overflow: "auto" }}>
                        {availableSchemas.map((s) => (
                          <Checkbox key={s} label={s} checked={selectedSchemas.has(s)} onChange={() => toggleSchema(s)} />
                        ))}
                      </div>
                    </>
                  )}
                </div>
              </>
            )}

            {error && (
              <Text style={{ color: tokens.colorPaletteRedForeground1 }}>{error}</Text>
            )}
            {testResult && (
              <Text style={{ color: testResult.ok ? tokens.colorPaletteGreenForeground1 : tokens.colorPaletteRedForeground1 }}>
                {testResult.ok ? `${t("connectedIn")} ${testResult.latencyMs}ms` : `${t("failure")}: ${testResult.message ?? t("unknownFailure")}`}
              </Text>
            )}
          </DialogBody>
          <DialogActions>
            {mode !== "demo" && (
              <Button type="button" onClick={onTest} disabled={busy || !canConnect()}>
                {busy ? t("loading") : t("connect")}
              </Button>
            )}
            <div style={{ flex: 1 }} />
            <Button type="button" onClick={onClose} disabled={busy}>
              {t("cancel")}
            </Button>
            <Button type="submit" appearance="primary" disabled={busy || (mode !== "demo" && !canConnect())}>
              {busy ? t("loading") : t("saveConnection")}
            </Button>
          </DialogActions>
        </form>
      </DialogSurface>
    </Dialog>
  );
}
