// apps/desktop/src/lib/FormatSettings.svelte
<!-- svelte-ignore state_referenced_locally -->
<script lang="ts">
  import {
    type FormatterSettings,
    DEFAULT_FORMATTER_SETTINGS,
    isValidKeybinding,
    formatKeybindingForDisplay,
    formatSql,
  } from "./format-sql.ts";
  import type { DialectId } from "@omni-sql/ts-types";
  import Settings from "@lucide/svelte/icons/settings";
  import X from "@lucide/svelte/icons/x";

  interface Props {
    open: boolean;
    dialect: DialectId;
    settings: FormatterSettings;
    onClose: () => void;
    onSave: (settings: FormatterSettings) => void;
  }
  let { open, dialect, settings, onClose, onSave }: Props = $props();

  let draft = $state<FormatterSettings>(structuredClone($state.snapshot(settings)));
  let keybindingError = $derived(
    isValidKeybinding(draft.keybinding) ? null : "Atalho inválido. Use pelo menos um modificador (Ctrl, Alt, Shift, Cmd).",
  );

  const PREVIEW_SQL = `SELECT id, name, email FROM users WHERE active = 1 AND created_at >= '2024-01-01' ORDER BY created_at DESC LIMIT 100;`;

  let preview = $derived.by(() => {
    try {
      return formatSql(PREVIEW_SQL, dialect, draft);
    } catch (e) {
      return `Erro no preview: ${(e as Error).message}`;
    }
  });

  function resetDefaults() {
    draft = DEFAULT_FORMATTER_SETTINGS;
  }

  function handleSubmit(e: Event) {
    e.preventDefault();
    if (keybindingError) return;
    onSave(draft);
  }

  const keywordCaseOptions = [
    { value: "preserve", label: "Preservar" },
    { value: "upper", label: "MAIÚSCULAS" },
    { value: "lower", label: "minúsculas" },
  ];

  const indentStyleOptions = [
    { value: "standard", label: "Padrão" },
    { value: "tabularLeft", label: "Tabular à esquerda" },
    { value: "tabularRight", label: "Tabular à direita" },
  ];

  const logicalOperatorOptions = [
    { value: "before", label: "Antes" },
    { value: "after", label: "Depois" },
  ];

  function bindSelect<K extends keyof FormatterSettings>(key: K) {
    return (e: Event) => {
      draft = { ...draft, [key]: (e.currentTarget as HTMLSelectElement).value } as FormatterSettings;
    };
  }

  function bindNumber<K extends keyof FormatterSettings>(key: K) {
    return (e: Event) => {
      const value = Number((e.currentTarget as HTMLInputElement).value);
      draft = { ...draft, [key]: value } as FormatterSettings;
    };
  }

  function bindBoolean<K extends keyof FormatterSettings>(key: K) {
    return (e: Event) => {
      draft = { ...draft, [key]: (e.currentTarget as HTMLInputElement).checked } as FormatterSettings;
    };
  }
</script>

{#if open}
  <div class="backdrop" onclick={onClose} role="presentation">
    <div
      class="modal"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => {
        if (e.key === "Escape") onClose();
      }}
      role="dialog"
      aria-modal="true"
      tabindex="-1"
    >
      <header class="header">
        <span class="title"><Settings size={15} /> Configurações do formatador SQL</span>
        <button class="icon close" type="button" onclick={onClose} aria-label="Fechar"><X size={14} /></button>
      </header>

      <form class="body" onsubmit={handleSubmit}>
        <section class="section">
          <h3>Atalho</h3>
          <label class="field">
            <span>Tecla de atalho</span>
            <input
              type="text"
              value={draft.keybinding}
              oninput={(e) => draft = { ...draft, keybinding: e.currentTarget.value }}
              class:error={!!keybindingError}
              placeholder="Ctrl+Alt+L"
            />
            {#if keybindingError}
              <span class="hint error">{keybindingError}</span>
            {:else}
              <span class="hint">Exemplos: Ctrl+Alt+L, Cmd+Shift+F, Ctrl+Shift+I</span>
            {/if}
          </label>
          <p class="display">Exibido como: <kbd>{formatKeybindingForDisplay(draft.keybinding)}</kbd></p>
        </section>

        <section class="section">
          <h3>Capitalização</h3>
          <div class="field-row">
            <label class="field compact">
              <span>Palavras-chave</span>
              <select value={draft.keywordCase} onchange={bindSelect("keywordCase")}>
                {#each keywordCaseOptions as opt}
                  <option value={opt.value}>{opt.label}</option>
                {/each}
              </select>
            </label>
            <label class="field compact">
              <span>Identificadores</span>
              <select value={draft.identifierCase} onchange={bindSelect("identifierCase")}>
                {#each keywordCaseOptions as opt}
                  <option value={opt.value}>{opt.label}</option>
                {/each}
              </select>
            </label>
            <label class="field compact">
              <span>Tipos de dados</span>
              <select value={draft.dataTypeCase} onchange={bindSelect("dataTypeCase")}>
                {#each keywordCaseOptions as opt}
                  <option value={opt.value}>{opt.label}</option>
                {/each}
              </select>
            </label>
            <label class="field compact">
              <span>Funções</span>
              <select value={draft.functionCase} onchange={bindSelect("functionCase")}>
                {#each keywordCaseOptions as opt}
                  <option value={opt.value}>{opt.label}</option>
                {/each}
              </select>
            </label>
          </div>
        </section>

        <section class="section">
          <h3>Layout</h3>
          <div class="field-row">
            <label class="field compact">
              <span>Estilo de indentação</span>
              <select value={draft.indentStyle} onchange={bindSelect("indentStyle")}>
                {#each indentStyleOptions as opt}
                  <option value={opt.value}>{opt.label}</option>
                {/each}
              </select>
            </label>
            <label class="field compact">
              <span>Largura da expressão</span>
              <input type="number" min="20" max="200" value={draft.expressionWidth} oninput={bindNumber("expressionWidth")} />
            </label>
            <label class="field compact">
              <span>Linhas entre queries</span>
              <input type="number" min="0" max="10" value={draft.linesBetweenQueries} oninput={bindNumber("linesBetweenQueries")} />
            </label>
            <label class="field compact">
              <span>Quebra do AND/OR</span>
              <select value={draft.logicalOperatorNewline} onchange={bindSelect("logicalOperatorNewline")}>
                {#each logicalOperatorOptions as opt}
                  <option value={opt.value}>{opt.label}</option>
                {/each}
              </select>
            </label>
          </div>
          <div class="field-row">
            <label class="field compact">
              <span>Largura do tab</span>
              <input type="number" min="1" max="8" value={draft.tabWidth} oninput={bindNumber("tabWidth")} />
            </label>
            <label class="checkbox">
              <input type="checkbox" checked={draft.useTabs} onchange={bindBoolean("useTabs")} />
              Usar tabs em vez de espaços
            </label>
            <label class="checkbox">
              <input type="checkbox" checked={draft.denseOperators} onchange={bindBoolean("denseOperators")} />
              Operadores densos
            </label>
            <label class="checkbox">
              <input type="checkbox" checked={draft.newlineBeforeSemicolon} onchange={bindBoolean("newlineBeforeSemicolon")} />
              Nova linha antes do ponto-e-vírgula
            </label>
          </div>
        </section>

        <section class="section">
          <h3>Preview ({dialect})</h3>
          <pre class="preview"><code>{preview}</code></pre>
        </section>

        <div class="actions">
          <button type="button" class="secondary" onclick={resetDefaults}>Restaurar padrão</button>
          <div class="spacer"></div>
          <button type="button" class="secondary" onclick={onClose}>Cancelar</button>
          <button type="submit" class="primary" disabled={!!keybindingError}>Salvar</button>
        </div>
      </form>
    </div>
  </div>
{/if}

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
  }
  .modal {
    display: flex;
    flex-direction: column;
    width: min(720px, 94vw);
    max-height: min(900px, 92vh);
    background: #1e1e1e;
    border: 1px solid #333;
    border-radius: 6px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.4);
    overflow: hidden;
  }
  .header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 14px;
    background: #2d2d30;
    border-bottom: 1px solid #333;
  }
  .title {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    font-weight: 600;
    color: #ddd;
  }
  .body {
    display: flex;
    flex-direction: column;
    padding: 14px;
    gap: 16px;
    overflow-y: auto;
  }
  .section h3 {
    margin: 0 0 8px;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: #888;
  }
  .field {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .field span {
    font-size: 12px;
    color: #9d9d9d;
  }
  .field input,
  .field select {
    background: #2d2d2d;
    border: 1px solid #3c3c3c;
    border-radius: 4px;
    color: #ddd;
    padding: 6px 8px;
    font-size: 13px;
    font-family: inherit;
  }
  .field input.error {
    border-color: #a1260d;
  }
  .field input:focus,
  .field select:focus {
    outline: 1px solid #0e639c;
  }
  .field-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 10px;
  }
  .field.compact input,
  .field.compact select {
    width: 100%;
  }
  .hint {
    font-size: 11px;
    color: #888;
  }
  .hint.error {
    color: #f48771;
  }
  .display {
    margin: 6px 0 0;
    font-size: 12px;
    color: #bbb;
  }
  kbd {
    background: #333;
    border: 1px solid #555;
    border-radius: 3px;
    padding: 2px 6px;
    font-family: ui-monospace, monospace;
    font-size: 11px;
  }
  .checkbox {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    color: #ccc;
    cursor: pointer;
  }
  .checkbox input {
    accent-color: #0e639c;
  }
  .preview {
    margin: 0;
    padding: 10px;
    background: #141414;
    border: 1px solid #333;
    border-radius: 4px;
    color: #d4d4d4;
    font-family: ui-monospace, monospace;
    font-size: 12px;
    line-height: 1.5;
    white-space: pre-wrap;
    max-height: 220px;
    overflow: auto;
  }
  .actions {
    display: flex;
    gap: 8px;
    padding-top: 4px;
  }
  .actions button {
    background: #2d2d2d;
    color: #ddd;
    border: 1px solid #3c3c3c;
    padding: 6px 12px;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
  }
  .actions button.primary {
    background: #0e639c;
    color: #fff;
    border-color: #0e639c;
  }
  .actions button.primary:hover:not(:disabled) {
    background: #1177bb;
  }
  .actions button:disabled {
    opacity: 0.5;
    cursor: default;
  }
  .actions .secondary:hover:not(:disabled) {
    background: #3c3c3c;
  }
  .spacer {
    flex: 1;
  }
  button.icon {
    background: transparent;
    border: none;
    color: #ccc;
    padding: 4px;
    cursor: pointer;
    display: inline-flex;
    align-items: center;
  }
  button.icon.close:hover {
    color: #fff;
  }
</style>

// apps/desktop/src/components/FormatSettings.tsx
import { useMemo, useState } from "react";
import {
  Button,
  Dialog,
  DialogSurface,
  DialogTitle,
  DialogBody,
  DialogActions,
  Input,
  Label,
  Select,
  Text,
  tokens,
} from "@fluentui/react-components";
import {
  DEFAULT_FORMATTER_SETTINGS,
  formatKeybindingForDisplay,
  formatSql,
  isValidKeybinding,
  type FormatterSettings,
} from "../lib/format-sql";
import type { DialectId } from "@omni-sql/ts-types";

export interface FormatSettingsProps {
  open: boolean;
  dialect: DialectId;
  settings: FormatterSettings;
  onClose: () => void;
  onSave: (settings: FormatterSettings) => void;
}

const keywordCaseOptions = [
  { value: "preserve", label: "Preservar" },
  { value: "upper", label: "MAIÚSCULAS" },
  { value: "lower", label: "minúsculas" },
];

const indentStyleOptions = [
  { value: "standard", label: "Padrão" },
  { value: "tabularLeft", label: "Tabular à esquerda" },
  { value: "tabularRight", label: "Tabular à direita" },
];

const logicalOperatorOptions = [
  { value: "before", label: "Antes" },
  { value: "after", label: "Depois" },
];

const PREVIEW_SQL = `SELECT id, name, email FROM users WHERE active = 1 AND created_at >= '2024-01-01' ORDER BY created_at DESC LIMIT 100;`;

export function FormatSettings({ open, dialect, settings, onClose, onSave }: FormatSettingsProps) {
  const [draft, setDraft] = useState<FormatterSettings>(() => ({ ...settings }));

  const keybindingError = useMemo(
    () => (isValidKeybinding(draft.keybinding) ? null : "Atalho inválido. Use pelo menos um modificador."),
    [draft.keybinding],
  );

  const preview = useMemo(() => {
    try {
      return formatSql(PREVIEW_SQL, dialect, draft);
    } catch (e) {
      return `Erro no preview: ${e instanceof Error ? e.message : String(e)}`;
    }
  }, [dialect, draft]);

  const update = <K extends keyof FormatterSettings>(key: K, value: FormatterSettings[K]) => {
    setDraft((prev) => ({ ...prev, [key]: value }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (keybindingError) return;
    onSave(draft);
  };

  return (
    <Dialog open={open} onOpenChange={(_, data) => !data.open && onClose()}>
      <DialogSurface style={{ maxWidth: 720 }}>
        <form onSubmit={handleSubmit}>
          <DialogTitle>Configurações do formatador SQL</DialogTitle>
          <DialogBody style={{ display: "flex", flexDirection: "column", gap: 16 }}>
            <div>
              <Label>Atalho</Label>
              <Input
                value={draft.keybinding}
                onChange={(_, data) => update("keybinding", data.value)}
                placeholder="Ctrl+Alt+L"
                style={{ borderColor: keybindingError ? tokens.colorPaletteRedBorder1 : undefined }}
              />
              {keybindingError ? (
                <Text style={{ color: tokens.colorPaletteRedForeground1, fontSize: 12 }}>{keybindingError}</Text>
              ) : (
                <Text size={200} style={{ color: tokens.colorNeutralForeground2 }}>
                  Exemplos: Ctrl+Alt+L, Cmd+Shift+F, Ctrl+Shift+I
                </Text>
              )}
              <div style={{ marginTop: 4 }}>
                Exibido como: <kbd>{formatKeybindingForDisplay(draft.keybinding)}</kbd>
              </div>
            </div>

            <div>
              <Label style={{ display: "block", marginBottom: 8 }}>Capitalização</Label>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
                {[
                  ["keywordCase", "Palavras-chave"],
                  ["identifierCase", "Identificadores"],
                  ["dataTypeCase", "Tipos de dados"],
                  ["functionCase", "Funções"],
                ].map(([key, label]) => (
                  <Label key={key}>
                    {label}
                    <Select
                      value={String(draft[key as keyof FormatterSettings])}
                      onChange={(_, data) => update(key as keyof FormatterSettings, data.value as never)}
                      style={{ display: "block", marginTop: 4 }}
                    >
                      {keywordCaseOptions.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </Select>
                  </Label>
                ))}
              </div>
            </div>

            <div>
              <Label style={{ display: "block", marginBottom: 8 }}>Layout</Label>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
                <Label>
                  Estilo de indentação
                  <Select value={draft.indentStyle} onChange={(_, data) => update("indentStyle", data.value as FormatterSettings["indentStyle"])} style={{ display: "block", marginTop: 4 }}>
                    {indentStyleOptions.map((opt) => (
                      <option key={opt.value} value={opt.value}>
                        {opt.label}
                      </option>
                    ))}
                  </Select>
                </Label>
                <Label>
                  Largura da expressão
                  <Input type="number" min={20} max={200} value={String(draft.expressionWidth)} onChange={(_, data) => update("expressionWidth", Number(data.value))} style={{ marginTop: 4 }} />
                </Label>
                <Label>
                  Linhas entre queries
                  <Input type="number" min={0} max={10} value={String(draft.linesBetweenQueries)} onChange={(_, data) => update("linesBetweenQueries", Number(data.value))} style={{ marginTop: 4 }} />
                </Label>
                <Label>
                  Quebra do AND/OR
                  <Select value={draft.logicalOperatorNewline} onChange={(_, data) => update("logicalOperatorNewline", data.value as FormatterSettings["logicalOperatorNewline"])} style={{ display: "block", marginTop: 4 }}>
                    {logicalOperatorOptions.map((opt) => (
                      <option key={opt.value} value={opt.value}>
                        {opt.label}
                      </option>
                    ))}
                  </Select>
                </Label>
              </div>
              <div style={{ display: "flex", gap: 16, marginTop: 12, alignItems: "center" }}>
                <Label>
                  Largura do tab
                  <Input type="number" min={1} max={8} value={String(draft.tabWidth)} onChange={(_, data) => update("tabWidth", Number(data.value))} style={{ width: 80, marginTop: 4 }} />
                </Label>
                <label style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <input type="checkbox" checked={draft.useTabs} onChange={(e) => update("useTabs", e.target.checked)} />
                  Usar tabs
                </label>
                <label style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <input type="checkbox" checked={draft.denseOperators} onChange={(e) => update("denseOperators", e.target.checked)} />
                  Operadores densos
                </label>
                <label style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <input type="checkbox" checked={draft.newlineBeforeSemicolon} onChange={(e) => update("newlineBeforeSemicolon", e.target.checked)} />
                  Nova linha antes do ;
                </label>
              </div>
            </div>

            <div>
              <Label>Preview ({dialect})</Label>
              <pre
                style={{
                  background: tokens.colorNeutralBackground1,
                  border: `1px solid ${tokens.colorNeutralStroke1}`,
                  borderRadius: 4,
                  padding: 10,
                  fontFamily: "ui-monospace, monospace",
                  fontSize: 12,
                  maxHeight: 220,
                  overflow: "auto",
                }}
              >
                {preview}
              </pre>
            </div>
          </DialogBody>
          <DialogActions>
            <Button type="button" onClick={() => setDraft(DEFAULT_FORMATTER_SETTINGS)}>
              Restaurar padrão
            </Button>
            <div style={{ flex: 1 }} />
            <Button type="button" onClick={onClose}>
              Cancelar
            </Button>
            <Button type="submit" appearance="primary" disabled={!!keybindingError}>
              Salvar
            </Button>
          </DialogActions>
        </form>
      </DialogSurface>
    </Dialog>
  );
}
